openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9

paths:
  /docs:
    get:
      summary: test.
      description: desciption API.
      responses:
        "200": # status code
          description: List of Player
          content:
            application/json:
              schema:
                type: string
  /student:
    get:
      summary: test.
      description: desciption API.
      responses:
        "200": # status code
          description: List of Player
          content:
            application/json:
              schema:
                type: string
